[settings]
idiomatic_version_file_enable_tools = []
experimental = true

[tools]
awscli = "latest"
cargo-binstall = "latest"
"cargo:alacritty" = "latest"
delta = "latest"
deno = "2.2.12"
bat = "latest"
direnv = "latest"
fd = "latest"
fzf = "latest"
go = "1.24.3"
java = "latest"
k9s = "latest"
kubectl = "latest"
lua-language-server = "latest"
minikube = "latest"
nodejs = ["22.18.0", "22.14.0"]
python = ["3.13.6", "3.12.3", "3.11.4", "3.13.1", "3.9.23"]
ripgrep = "latest"
sqlite = "latest"
terraform = "latest"
terraform-ls = "latest"
tree-sitter = "latest"
yarn = "1.22.22"
"cargo:dioxus-cli" = "latest"
"go:github.com/openfga/cli/cmd/fga" = "latest"
"github:neovim/neovim" = "nightly"
"npm:pnpm" = "latest"
"npm:bash-language-server" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:svelte-language-server" = "latest"
"npm:@modelcontextprotocol/server-filesystem" = "latest"
"npm:@modelcontextprotocol/server-sequential-thinking" = "latest"
"npm:mint" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:prettier" = "latest"
"npm:prettier-plugin-svelte" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vim-language-server" = "latest"
"pipx:aider-chat" = { version = "latest", uvx_args = "--python 3.12 --with boto3" }
"pipx:basedpyright" = "latest"
"pipx:grip" = "latest"
"pipx:poetry" = { version = "latest", uvx_args = "--with poetry-plugin-export" }
"pipx:pre-commit" = "latest"
"pipx:mcp-server-git" = "latest"
"pipx:doc2dash" = "latest"
"pipx:mkdocs" = { version = "latest", uvx_args = "--with mkdocs-material" }
"pipx:poethepoet" = "latest"

[tasks]
install-playwright-mcp = "npm install -g @playwright/mcp"
