[settings]
idiomatic_version_file_enable_tools = []
experimental = true

[settings.npm]
package_manager = "bun"

[tools]
awscli = "latest"
cargo-binstall = "latest"
"cargo:alacritty" = "latest"
claude = "latest"
delta = "latest"
deno = "2.2.12"
bat = "latest"
direnv = "latest"
fd = "latest"
fzf = "latest"
go = "1.24.3"
java = "latest"
k9s = "latest"
kubectl = "latest"
lua-language-server = "latest"
minikube = "latest"
nodejs = ["24.13.0"]
pnpm = "latest"
python = ["3.14.2", "3.13.11", "3.12.12"]
ripgrep = "latest"
sqlite = "latest"
terraform = "latest"
terraform-ls = "latest"
tree-sitter = "latest"
yarn = "1.22.22"
zig = "0.15"
zls = "0.15"
"cargo:dioxus-cli" = "latest"
"go:github.com/openfga/cli/cmd/fga" = { version = "latest" }
"github:neovim/neovim" = "nightly"
"npm:bash-language-server" = "latest"
"npm:svelte-language-server" = "latest"
"npm:mint" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:prettier" = "latest"
"npm:prettier-plugin-svelte" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vim-language-server" = "latest"
"pipx:aider-chat" = { version = "latest", uvx_args = "--python 3.12 --with boto3" }
"pipx:basedpyright" = "latest"
"pipx:ty" = "latest"
"pipx:grip" = "latest"
"pipx:poetry" = { version = "latest", uvx_args = "--with poetry-plugin-export" }
"pipx:pre-commit" = "latest"
"pipx:doc2dash" = "latest"
"pipx:mkdocs" = { version = "latest", uvx_args = "--with mkdocs-material" }
"pipx:poethepoet" = "latest"
